// Sparse demo data for OuroNova MVP
window.OURO_DATA = {
  // Sample marketplace listings (France)
  listings: [
    {
      id: 'lst-001',
      title: 'Solid oak kitchen cabinets, 4.2m run',
      material: 'Reclaimed Oak',
      grade: 'A',
      price: 480,
      retailEquiv: 1850,
      qty: '12 units',
      city: 'Paris 11e',
      distanceKm: 6,
      seller: 'Atelier Voltaire',
      sellerRating: 4.9,
      sellerJobs: 23,
      year: 2014,
      hazard: false,
      desc: 'Removed from a private Haussmann apartment renovation. Doors intact, hinges included. Some scratches on lower units; sanded surface ready for refinish.',
      tags: ['kitchen', 'wood', 'cabinetry'],
      pickup: 'Available weekday afternoons. Van access via courtyard.',
      photo: 'oak',
      co2Saved: 142,
    },
    {
      id: 'lst-002',
      title: 'Copper piping offcuts, ~38kg',
      material: 'Copper',
      grade: 'B',
      price: 220,
      retailEquiv: 540,
      qty: '~38 kg',
      city: 'Lyon 3e',
      distanceKm: 18,
      seller: 'Plomberie Garnier',
      sellerRating: 4.7,
      sellerJobs: 41,
      year: 2022,
      hazard: false,
      desc: 'Mixed lengths from a recent residential refit. Cleaned, no solder residue. Ideal for art projects or small plumbing repairs.',
      tags: ['metal', 'plumbing', 'copper'],
      pickup: 'Saturday mornings, by appointment.',
      photo: 'copper',
      co2Saved: 88,
    },
    {
      id: 'lst-003',
      title: 'Vintage Carrara marble countertop, 2.4m',
      material: 'Carrara Marble',
      grade: 'A',
      price: 690,
      retailEquiv: 2400,
      qty: '1 slab',
      city: 'Marseille 7e',
      distanceKm: 32,
      seller: 'Renov\'Sud',
      sellerRating: 4.8,
      sellerJobs: 17,
      year: 1998,
      hazard: false,
      desc: 'Single piece, 2400×640×30mm. Light staining near sink cutout, easily polished out. Original beveled edge.',
      tags: ['stone', 'kitchen', 'countertop'],
      pickup: 'Forklift required. Loading bay on-site.',
      photo: 'marble',
      co2Saved: 215,
    },
    {
      id: 'lst-004',
      title: 'Industrial steel beams, IPN 200',
      material: 'Structural Steel',
      grade: 'C',
      price: 340,
      retailEquiv: 920,
      qty: '6 × 3.2m beams',
      city: 'Bordeaux',
      distanceKm: 9,
      seller: 'BTP Garonne',
      sellerRating: 4.6,
      sellerJobs: 88,
      year: 1985,
      hazard: false,
      desc: 'Recovered from warehouse demolition. Surface oxidation present, structural integrity verified by site engineer (cert. on request).',
      tags: ['metal', 'structural'],
      pickup: 'Crane truck recommended. Coordinated delivery available (+€80).',
      photo: 'steel',
      co2Saved: 1240,
    },
    {
      id: 'lst-005',
      title: 'Reclaimed terracotta floor tiles',
      material: 'Terracotta',
      grade: 'A',
      price: 290,
      retailEquiv: 780,
      qty: '~14 m²',
      city: 'Toulouse',
      distanceKm: 14,
      seller: 'Maison Cazes',
      sellerRating: 5.0,
      sellerJobs: 8,
      year: 1978,
      hazard: true,
      hazardNote: 'Pre-1990, recommend lead-paint test on grout (€140).',
      desc: 'Hand-made hexagonal tiles from a Languedoc farmhouse. Beautiful warm patina. Sold as full lot.',
      tags: ['ceramic', 'flooring', 'heritage'],
      pickup: 'Already palletized. Self-pickup with utility vehicle.',
      photo: 'terracotta',
      co2Saved: 96,
    },
    {
      id: 'lst-006',
      title: 'Cast iron radiators × 4',
      material: 'Cast Iron',
      grade: 'B',
      price: 180,
      retailEquiv: 720,
      qty: '4 units',
      city: 'Lille',
      distanceKm: 22,
      seller: 'Renov Nord',
      sellerRating: 4.5,
      sellerJobs: 31,
      year: 1962,
      hazard: false,
      desc: 'Tested at 6 bar, fully functional. Original cream paint flaking, sandblasting recommended before repaint.',
      tags: ['heating', 'metal', 'heritage'],
      pickup: 'Disassembled, on pallets.',
      photo: 'radiator',
      co2Saved: 320,
    },
  ],

  // French renovation policies, actual 2026 schemes
  subsidies: [
    {
      id: 'mpr-ampleur',
      name: "MaPrimeRénov' Parcours Accompagné",
      tag: 'Major renovation',
      max: 70000,
      typical: 18500,
      desc: 'Up to 90% covered for very-modest households doing ambitious multi-step renovations (≥2 DPE class gain). Paid by ANAH.',
      eligibility: ['Home ≥15 years old', 'Primary residence', '≥2 DPE class improvement', 'RGE-certified contractor', 'Energy audit required'],
      timeline: '8–16 weeks via ANAH',
      match: 0.94,
      stat: 'Only 23% of eligible Île-de-France households apply.',
    },
    {
      id: 'mpr-geste',
      name: "MaPrimeRénov' Parcours par Geste",
      tag: 'Targeted works',
      max: 12000,
      typical: 4200,
      desc: 'Single-element works: heat pump, insulation, ventilation. Means-tested (Bleu / Jaune / Violet / Rose).',
      eligibility: ['Home ≥15 years old', 'Primary residence', 'RGE contractor', 'Quote signed AFTER application'],
      timeline: '4–8 weeks',
      match: 0.88,
      stat: '68% of eligible owners never claim, most cite paperwork friction.',
    },
    {
      id: 'cee',
      name: "Certificats d'Économies d'Énergie (CEE)",
      tag: 'Energy supplier bonus',
      max: 5000,
      typical: 2400,
      desc: '10–20% of works cost paid directly by EDF, TotalEnergies, etc. Not means-tested. Stackable with MaPrimeRénov\u2019.',
      eligibility: ['Any homeowner or tenant', 'RGE-certified works', 'Bio-sourced materials get bonus'],
      timeline: 'Often deducted from invoice',
      match: 1.0,
      stat: 'Bio-sourced insulation (wood wool, hemp) earns +10% bonus.',
    },
    {
      id: 'eco-ptz',
      name: 'Éco-PTZ: Prêt à Taux Zéro',
      tag: 'Zero-interest loan',
      max: 50000,
      typical: 28000,
      desc: 'Zero-interest loan to cover the rest-to-pay after subsidies. No income test. Up to 20-year repayment.',
      eligibility: ['Home ≥2 years old', 'Primary residence', 'RGE contractor required'],
      timeline: '3–6 weeks (via partner banks)',
      match: 0.92,
      stat: 'Combined with MaPrimeRénov\u2019, drops out-of-pocket cost by 70%+.',
    },
    {
      id: 'tva-5-5',
      name: 'TVA réduite à 5,5%',
      tag: 'Reduced VAT',
      max: 4500,
      typical: 1800,
      desc: 'Reduced VAT (5.5% vs. 20%) on energy-efficiency works in homes >2 years old. Applied automatically by RGE contractor.',
      eligibility: ['Home >2 years old', 'Energy-efficiency works only', 'RGE contractor'],
      timeline: 'Applied at invoicing',
      match: 1.0,
      stat: 'Saves €14.50 on every €100 of qualifying labor.',
    },
    {
      id: 'local',
      name: 'Aides locales Île-de-France',
      tag: 'Regional bonus',
      max: 3500,
      typical: 1200,
      desc: 'Top-up grants from Région Île-de-France + your commune. Often unknown by applicants, check separately.',
      eligibility: ['Resident of Île-de-France', 'Stackable with national aids'],
      timeline: '6–10 weeks',
      match: 0.72,
      stat: '4 in 5 applicants miss this layer entirely.',
    },
  ],

  // Cost tiers, kitchen renovation example
  costTiers: [
    {
      key: 'budget',
      label: 'Budget',
      range: [3800, 6200],
      desc: 'Mostly reclaimed materials, IKEA-style frames, DIY assembly.',
      breakdown: [
        { item: 'Reclaimed oak fronts', cost: 480, recycled: true },
        { item: 'IKEA Metod cabinets', cost: 1200, recycled: false },
        { item: 'Reclaimed countertop', cost: 690, recycled: true },
        { item: 'Salvaged sink + tap', cost: 140, recycled: true },
        { item: 'Labour (3 days)', cost: 1100, recycled: false },
        { item: 'Tiles, fixings, paint', cost: 320, recycled: false },
      ],
      co2: 1.4,
      recycledPct: 62,
      subsidies: 1800,
    },
    {
      key: 'mid',
      label: 'Mid-range',
      range: [7800, 12400],
      desc: 'Mix of reclaimed and new, quartz, induction, mid-tier appliances.',
      breakdown: [
        { item: 'Custom oak fronts (reclaimed)', cost: 1800, recycled: true },
        { item: 'New cabinet frames', cost: 2400, recycled: false },
        { item: 'Quartz countertop', cost: 1900, recycled: false },
        { item: 'Induction hob + oven', cost: 1400, recycled: false },
        { item: 'Labour (5 days)', cost: 2200, recycled: false },
        { item: 'Tiles, fittings, paint', cost: 700, recycled: false },
      ],
      co2: 3.2,
      recycledPct: 28,
      subsidies: 2400,
    },
    {
      key: 'premium',
      label: 'Premium',
      range: [16500, 24000],
      desc: 'Custom cabinetry, marble, integrated appliances, designer fixtures.',
      breakdown: [
        { item: 'Bespoke cabinetry', cost: 8400, recycled: false },
        { item: 'Carrara marble', cost: 3800, recycled: false },
        { item: 'Premium appliances', cost: 4800, recycled: false },
        { item: 'Labour (8 days)', cost: 3600, recycled: false },
        { item: 'Tiles, fixtures, lighting', cost: 1900, recycled: false },
      ],
      co2: 6.8,
      recycledPct: 4,
      subsidies: 1200,
    },
  ],

  // Impact dashboard sample
  impact: {
    co2Saved: 4.2, // tonnes
    wasteDiverted: 1.8, // tonnes
    subsidiesUnlocked: 3200, // euros
    moneySaved: 2840,
    rank: 'Top 8% in Île-de-France',
    history: [
      { month: 'Nov', co2: 0.4 },
      { month: 'Dec', co2: 0.6 },
      { month: 'Jan', co2: 0.5 },
      { month: 'Feb', co2: 0.9 },
      { month: 'Mar', co2: 1.2 },
      { month: 'Apr', co2: 0.6 },
    ],
    activity: [
      { date: 'Apr 22', text: 'Listed: solid oak kitchen cabinets', meta: '+142 kg CO₂ avoided' },
      { date: 'Apr 14', text: 'Subsidy match: MaPrimeRénov\' Isolation', meta: '€3,200 unlocked' },
      { date: 'Apr 09', text: 'Purchase: reclaimed terracotta tiles', meta: '€290,96 kg CO₂ saved' },
      { date: 'Mar 28', text: 'Photo analysis: kitchen renovation', meta: '3 estimates generated' },
    ],
  },

  // Hardcoded photo analysis result, enriched with upgrade plan + circular materials + policy match
  photoAnalysis: {
    room: 'Kitchen',
    sqm: 14,
    yearBuilt: 1972,
    dpe: 'F: Thermal sieve',
    dpePotential: 'C',
    detected: [
      { item: 'Laminate cabinet fronts', condition: 'Worn: replace', salvage: false, age: '~15 yrs' },
      { item: 'Stainless steel sink', condition: 'Good: keep or relist', salvage: true, age: '~8 yrs' },
      { item: 'Tiled splashback', condition: 'Dated: strip', salvage: false, age: '~25 yrs' },
      { item: 'Linoleum flooring', condition: 'Damaged: dispose', salvage: false, age: '~20 yrs' },
      { item: 'Single-glazed window', condition: 'Major heat loss', salvage: false, age: '~50 yrs' },
      { item: 'Old electric radiator', condition: 'Inefficient: replace', salvage: false, age: '~22 yrs' },
    ],
    upgrades: [
      {
        what: 'Replace single-glazed window with double-glazed',
        why: 'Cuts ~22% of heating energy loss. Required to escape DPE class F.',
        cost: 1850,
        co2: 0.34,
        priority: 'high',
      },
      {
        what: 'Install air-source heat pump (replaces electric radiators)',
        why: 'Largest single subsidy lever. CEE + MPR\u2019 stack up to €15,000.',
        cost: 9200,
        co2: 1.8,
        priority: 'high',
      },
      {
        what: 'Insulate exterior wall (ITE) with bio-sourced wood wool',
        why: 'Bio-sourced bonus: +10% MaPrimeRénov\u2019. Eligible for CEE bonus.',
        cost: 4400,
        co2: 0.95,
        priority: 'medium',
      },
      {
        what: 'Replace cabinetry with reclaimed oak (3 buyers within 8 km)',
        why: 'Saves €1,370 vs. new. 142 kg CO\u2082 avoided. Marketplace match available now.',
        cost: 480,
        co2: 0.14,
        priority: 'medium',
      },
    ],
    circularMatches: [
      { material: 'Reclaimed oak cabinets', distance: 6, price: 480, retail: 1850, listingId: 'lst-001' },
      { material: 'Carrara marble countertop', distance: 32, price: 690, retail: 2400, listingId: 'lst-003' },
      { material: 'Cast iron radiators', distance: 22, price: 180, retail: 720, listingId: 'lst-006' },
    ],
    policyMatch: {
      stackedTotal: 21800,
      worksTotal: 32500,
      outOfPocket: 10700,
      schemes: [
        { id: 'mpr-ampleur', amount: 14400, label: "MaPrimeRénov\u2019 Parcours Accompagné" },
        { id: 'cee', amount: 3200, label: 'CEE: EDF « Coup de pouce »' },
        { id: 'tva-5-5', amount: 2640, label: 'TVA réduite 5,5%' },
        { id: 'local', amount: 1560, label: 'Aide Région Île-de-France' },
      ],
    },
    materialEstimate: '1.4 tonnes demolition material, €280 disposal cost OR €410 marketplace value',
    confidence: 0.86,
  },
};
